[Font]
DefaultFont         = resources/bell-mt.ttf
KennyPixel          = resources/fonts/Kenney_Pixel.ttf
KennyPixelSquared   = resources/fonts/Kenney_Pixel_Square.ttf

#with SFML texture can be use as sprite sheet, for anim use sprite sheet type
[Texture]
T_Default_3232      = resources/T_Default_3232.png
T_Default_6464      = resources/T_Default_6464.png
T_CharacterGreen    = resources/arts/SS_Character_Green_3232.png

# Multiline Save
#Sprite Sheet: 
# for simplicity sprite sheet will be use only for anims, horizontally
# always load texture before sprite sheet
# Example = Texture section key name e.g T_Default_3232
# Example = image size. keep it square. e.g 32 on 4 frame png size will be 128x32
# Example = numberOfFrame
[SpriteSheet]
GreenCharacter = T_CharacterGreen
GreenCharacter = 32
GreenCharacter = 2