#string AssetType, string Asset Name (should be unique), string Asset path
[Font]
Default             = resources/bell-mt.ttf
KennyPixel          = resources/fonts/Kenney_Pixel.ttf
KennyPixelSquared   = resources/fonts/Kenney_Pixel_Square.ttf
