#include "Sandbox.h"

#include "Engine/Modules/ModuleRegistrar.h"
#include "Components/GunComponent.h"
#include "Components/HealthComponent.h"
#include "Components/TagsComponent.h"
#include "Resources/WaveResource.h"
#include "Systems/HudSubsystem.h"
#include "Systems/PauseMenuSubsystem.h"
#include "Systems/PlayerControlSubsystem.h"
#include "Systems/QuadOscillatorSubsystem.h"
#include "Core/Log/Logger.h"  // OPAAX_LOG + LogCategory

using namespace Opaax;

namespace
{
    constexpr LogCategory LogSandboxModule{"SandboxModule"};
}

void SandboxModule::OnRegister(Opaax::ModuleRegistrar& InRegistrar)
{
    // A component the GAME owns — the engine has never heard of HealthComponent, yet it
    // round-trips through capture/instantiate like any native type. That is the whole point
    // of the route: satisfying CComponent is the entire contract.
    //
    // NOTE: DummyComponent is deliberately NOT registered here any more. It is an engine
    // type, and the engine registers its own natives first (MR2) — asking again would be
    // refused as a duplicate.
    InRegistrar.Components().Register<Sandbox::HealthComponent>();

    // The first caller of OpaaxTag (I14). Nothing new is needed to make it serializable: an
    // OpaaxTagContainer writes as an array of strings, so a tag is readable in the .opaaxmap.
    InRegistrar.Components().Register<Sandbox::TagsComponent>();

    // The first HARD reference (⑦-C P5b): the registry finds `Bullet` by its type at this line,
    // and a level mounting a map that carries a gun holds its bullet prefab from then on.
    InRegistrar.Components().Register<Sandbox::GunComponent>();

    // A world subsystem the ENGINE has never heard of. Play-only: it exists in a Play world and is
    // never constructed in an Edit one (WS1/WS2). Registering costs one line — no base-class
    // ceremony, no reflection, no static-init.
    //
    // NOTE: this is the only world-subsystem candidate in either host now. The Edit-only
    // QuadBoundsSubsystem that used to make SandboxEditor.exe's count two was deleted on
    // 2026-08-31 — see SandboxEditorModule.cpp for what that costs.
    //InRegistrar.WorldSubsystems().Register<Sandbox::QuadOscillatorSubsystem>();

    // ⑦-A P5b — the game's side of the mover seam: keys in, MoverInput out. It is also what
    // puts a caller back on this route, which has had none in either host since the line above
    // was commented out.
    InRegistrar.WorldSubsystems().Register<Sandbox::PlayerControlSubsystem>();

    // UI U2 — the first HUD: a jump counter and a speed bar under the GameInstance's canvas.
    InRegistrar.WorldSubsystems().Register<Sandbox::HudSubsystem>();

    // UI U3 — the first menu: a HUD button (GameAndUI) and a dimmed modal (UIOnly). One owner for it;
    // the Menu mapping context PlayerControl used to push is superseded by the real thing.
    InRegistrar.WorldSubsystems().Register<Sandbox::PauseMenuSubsystem>();

    // A resource type the ENGINE has never heard of, claiming its own extension. This is what makes
    // `.wave` a known file everywhere at once — the browser names it, and the editor module adds
    // only an icon. Registering it here rather than editor-side is deliberate: a wave is game
    // CONTENT, so Sandbox.exe must know it too.
    InRegistrar.Resources().Register<Sandbox::WaveResource>();

    OPAAX_LOG(LogSandboxModule, Info,
        "RegisterModule: components={}, worldSubsystems={}, resourceFormats={}",
        InRegistrar.Components().Count(), InRegistrar.WorldSubsystems().Count(),
        InRegistrar.Resources().Count());
}

// NOTE: SpawnDemoWorld is GONE (M5 S3). The three quads it built in C++ now live in
// Sandbox/Assets/Maps/Main.opaaxmap, composed by Assets/Levels/Main.opaaxlevel, which the
// project's `startupLevel` names and IEngine::FinishStartup opens — for BOTH hosts, from the
// one file. A module that spawned the world in code could only ever be edited by recompiling
// it, which is the thing the whole milestone exists to end.
//
// The map was GENERATED by this very function on its last run, captured through the real
// ComponentRegistry, so the component keys in it ("Dummy", "HealthComponent") are the names the
// registry actually derives rather than names anyone typed into a file.
