#include "Sandbox.h"

#include "Engine/Modules/ModuleRegistrar.h"
#include "Components/HealthComponent.h"
#include "Components/TagsComponent.h"
#include "Systems/QuadOscillatorSubsystem.h"
#include "Application/Services/ILogger.h"  // OPAAX_LOG + LogCategory

// OPAAX_LOG expands to an unqualified ToSpdLevel(...) — bring Opaax into scope, as engine TUs do.
using namespace Opaax;

namespace
{
    constexpr LogCategory LogSandboxModule{"SandboxModule"};
}

void SandboxModule::OnRegister(Opaax::ModuleRegistrar& InRegistrar)
{
    // A component the GAME owns — the engine has never heard of HealthComponent, yet it
    // round-trips through capture/instantiate like any native type. That is the whole point
    // of the route: satisfying CComponent is the entire contract.
    //
    // NOTE: DummyComponent is deliberately NOT registered here any more. It is an engine
    // type, and the engine registers its own natives first (MR2) — asking again would be
    // refused as a duplicate.
    InRegistrar.Components().Register<Sandbox::HealthComponent>();

    // The first caller of OpaaxTag (I14). Nothing new is needed to make it serializable: an
    // OpaaxTagContainer writes as an array of strings, so a tag is readable in the .opaaxmap.
    InRegistrar.Components().Register<Sandbox::TagsComponent>();

    // A world subsystem the ENGINE has never heard of. Play-only: it exists in a Play world and is
    // never constructed in an Edit one (WS1/WS2). Registering costs one line — no base-class
    // ceremony, no reflection, no static-init.
    //
    // NOTE: the Edit-only QuadBoundsSubsystem is NOT here any more (M4 S5). An authoring overlay is
    // EDITOR content, so it moved to the SandboxEditor module and registers through
    // EditWorldSystems() — a different route into the SAME registry. Sandbox.exe therefore has one
    // candidate and SandboxEditor.exe has two, which is the model's point stated as a build fact.
    InRegistrar.WorldSubsystems().Register<Sandbox::QuadOscillatorSubsystem>();

    OPAAX_LOG(LogSandboxModule, Info,
        "RegisterModule: components={}, worldSubsystems={}",
        InRegistrar.Components().Count(), InRegistrar.WorldSubsystems().Count());
}

// NOTE: SpawnDemoWorld is GONE (M5 S3). The three quads it built in C++ now live in
// Sandbox/Assets/Maps/Main.opaaxmap, composed by Assets/Levels/Main.opaaxlevel, which the
// project's `startupLevel` names and IEngine::FinishStartup opens — for BOTH hosts, from the
// one file. A module that spawned the world in code could only ever be edited by recompiling
// it, which is the thing the whole milestone exists to end.
//
// The map was GENERATED by this very function on its last run, captured through the real
// ComponentRegistry, so the component keys in it ("Dummy", "HealthComponent") are the names the
// registry actually derives rather than names anyone typed into a file.
